language: c
compiler:
  - gcc
  - clang
before_script:
  - mkdir _build
  - cd _build
script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ] ; then cmake .. -DCMAKE_C_COMPILER=$CC -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Continuous ; fi
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ] ; then make ; fi
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ] ; then make test ; fi
after_success:
  - ./coveralls-upload
# trigger Buildtime Trend Service to parse Travis CI log
notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
# use docker based faster build
sudo: false
# install build dependencies and enable Coverity scan
addons:
  apt:
    packages:
    - libbluetooth-dev
    - libusb-1.0-0-dev
    - libgudev-1.0-dev
    - unixodbc-dev
    - libdbi-dev
    - libdbd-sqlite3
  coverity_scan:
    project:
      name: "gammu/gammu"
      description: "Build submitted via Travis CI"
    notification_email: michal@cihar.com
    build_command_prepend: cmake ..
    build_command: make
    branch_pattern: coverity_scan
